# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170921_1205'),
        ('accounts', '0008_auto_20170921_0726'),
    ]

    operations = [
    ]
