# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='user',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
