# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170912_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='nag_time',
        ),
        migrations.RemoveField(
            model_name='check',
            name='next_nag_time',
        ),
    ]
