# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170914_1424'),
        ('api', '0027_auto_20170914_0715'),
    ]

    operations = [
    ]
