# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20170915_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('nag', 'nag'), ('often', 'Often')], default='new', max_length=6),
        ),
    ]
