# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20170921_0726'),
        ('api', '0030_auto_20170919_1332'),
    ]

    operations = [
    ]
