# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20170922_1341'),
        ('api', '0031_merge_20170922_0727'),
    ]

    operations = [
    ]
