# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_blogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
