# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_delete_blogs'),
        ('api', '0030_auto_20170919_1332'),
    ]

    operations = [
    ]
